"""
This file runs a very simple simulation to compare the upper bound generated by using the method found in Open-World Probabilistic Databases (Ceylan et. Al, 2016) with a method which uses summary statistics.

"""

import sys

def main():
    pass



if __name__ == '__main__':
    sys.exit(main())
